jhillyerd/enmime

charsets.go
Fixes issue #17 but unfortunately I don't have any tests for the new charsets added.
=> support more charset mappings

envelope_test.go, testdata/mail/ctype-bug.raw
@jhillyerd Interesting that your test case passes fine. I downloaded the original message from gmail and it parses fine but the headers are definitely being parsed incorrectly. I have added a test case.
More curiously when I download the email using https://github.com/mxk/go-imap and then parse that using enmime then I see the following message in the logs - "Failed to ReadParts: mime: invalid media parameter" but it does seem to parse it correctly (except the headers of course).
=> test case for headers being parsed wrongly, reported in issue #18

part.go
cf. issue "Set the Part boundary field for the Envelope's root" https://github.com/jhillyerd/enmime/issues/40
=> Set the Part boundary field for the Envelope's root

envelope.go, envelope_test.go, internal/test/testing.go, part.go, part_test.go
This kind of supersedes PR #65 (I don't have access to pedrinimm's branch). Will look into the mentioned boundary issue separately.
=> allow to clone envelopes

envelope.go, envelope_test.go
We need to be able to update headers in our application, so I implemented these functions. Please let me know what you think about it or if anything should be changed. Thanks for your time!
=> Functions to interact with headers: Replace, Add, Delete, Get all values

cmd/mime-dump/mime-dump.go, cmd/mime-extractor/mime-extractor.go
This fixes  #57.
was fairly straight forward, I have tested the changes compile and the code builds and runs, on Mac.
=> Use filepath and not url when dealing with files

boundary.go, envelope.go, error_test.go, go.mod, go.sum, header.go, part.go, part_test.go
=> Wrapping errors with errors.WithStack()

detect.go
Updated "detectAttachmentHeader" doc comment to, more accurately, depict the function flow
=> Resolves #86

envelope_test.go, part.go, testdata/mail/mime-bad-content-transfer-encoding.raw
=> Make decoding failure on base64.CorruptInputError non-fatal

inspect.go, inspect_test.go, part_test.go, testdata/mail/qp-utf8-header-recursed.raw
#64 Proposed Solution
Obviously the function name is up for debate, but this is the general flow
I noticed that the main lib doesn't yet support recursive rfc2047 encoded header values, so that will need to get incorporated into the ReadEnvelope flow as well
=> added public HumanHeadersOnly package-level function

boundary_test.go, builder_test.go, cmd/mime-dump/mime-dump.go, cmd/mime-dump/mime-dump_test.go, cmd/mime-extractor/mime-extractor.go, cmd/mime-extractor/mime-extractor_test.go, encode_test.go, envelope_test.go, error_test.go, inspect_test.go, internal/stringutil/unicode.go, part_test.go, testdata/encode/part-content-only-qp.golden, testdata/encode/part-header-only-default-encoding.golden, testdata/encode/part-quoted-printable-headers.golden, testdata/low-quality/bad-header-start.raw, testdata/mail/erroneous.raw, testdata/mail/qp-utf8-header-no-break.raw
Just trying to get that test coverage number up
=> Increase test coverage

header.go, header_test.go
=> Revert accidental continuation detection

boundary.go, internal/coding/quotedprint.go, part.go
This is in preparation for introducing more thorough static checks on PRs.
=> Correct shadowed errors

envelope.go, envelope_test.go, internal/coding/base64.go, internal/coding/charsets.go
This is in preparation for introducing more thorough static checks on PRs.
=> Fix capitalized error strings

.github/workflows/build-and-test.yml, .github/workflows/pull-checks.yml
Fixed the indentation issue and the Actions are passing on my fork. Sorry about that :)
=> Issue 188 failing GitHub actions

cmd/mime-dump/mime-dump.go, cmd/mime-dump/mime-dump_test.go
=> mime-dump: Add stack trace for errors

internal/coding/quotedprint.go, internal/coding/quotedprint_test.go
- QPCleaner: support tiny destination buffers
- QPCleaner: break long lines
Fixes #185
=> Resolve QPCleaner issues

header.go, header_test.go
=> header: Do not preserve param value unquoted leading whitespace

header.go, header_test.go
=> header: Quote values with spaces

header.go, inspect.go, internal/coding/headerext.go, internal/coding/headerext_test.go
- Move rfc2047 decoding into internal/coding package
- Tidy formatting/comments
- Rename existing decode tests
- Add rfc2047 specific test
=> Move RFC2047 decoding into internal/coding package

.golangci.yml, builder_test.go, encode.go, envelope.go, envelope_test.go, example_test.go, header.go, mediatype/mediatype.go
=> Fix linter issues

.github/workflows/lint.yml
=> Run linter on PR

builder.go
Hi, this PR is to implement the field accessors for `MailBuilder` as proposed in #260
=> feat: add field accessors for mailbuilder

.github/workflows/lint.yml
=> Fix golangci-lint build

.github/workflows/lint.yml, envelope.go
Blocked until https://github.com/golangci/golangci-lint-action/issues/535 is fixed
=> Update golangci-lint to 1.51.0

.envrc, .gitignore
=> Add direnv nix flake config

builder.go, internal/stringutil/rand_source.go
=> Refactor a couple parts of the boundary random sourcing

internal/textproto/reader.go, internal/textproto/reader_email.go, internal/textproto/reader_test.go, internal/textproto/writer.go
Cleanup lints go source import triggered after #282 #283
=> Fix lint errors introduced by textproto import

.github/workflows/build-and-test.yml, README.md
- ci: Test on push so we can have a badge for `main`
- Update build status badge for GH actions
=> README: Update CI status badge

dsn/dsn.go
Noticed a small type when looking at the code :)
=> Fix RecipientDSN typo

flake.lock
=> nix: update flake deps

example_test.go
=> tests: add output to ExampleBuilder

mediatype/mediatype.go
=> mediatype: add missing comment

envelope.go, internal/coding/quotedprint_test.go, internal/stringutil/find.go, internal/stringutil/wrap_test.go
- fix: don't shadow len() built-in
- style: remove whitespace
- envelope: remove unused error return
For #320
=> chore: resolve some linter issues

.github/dependabot.yml
=> actions: add dependabot config

Makefile
=> build: disable golint

options.go, parser.go, part.go, part_test.go
Allows for changing from the default 100 chars.
=> feat: add option to control minimum charset detect length

envelope.go, error.go, error_test.go, part.go
=> chore: resolve govet dynamic fmt string warning

.github/workflows/lint.yml, .golangci.yml, boundary_test.go, encode_test.go, internal/stringutil/wrap.go, options.go
=> chore: linter config update

header.go, options_test.go
=> chore!: remove deprecated ParseMediaType func

.github/workflows/build-and-test.yml, .github/workflows/lint.yml
=> chore: test with go 1.23

flake.lock
=> chore: bump flake deps

builder_test.go, cmd/mime-dump/mime-dump_test.go
=> chore: fix linter warnings

go.mod, go.sum
=> chore: bump go deps
