- boundary.go
- boundary_test.go
When attempting to parse a multipart email where the boundary doesn't exist, enmime gets stuck in an infinite loop.
I have created a test and implemented a fix. Feel free to reject and implement in your own manner! :)
> Allow for nonexistent boundary

- envelope_test.go
- example_test.go
- header.go
- testdata/mail/qp-utf8-header.raw
Added remaining address headers from https://tools.ietf.org/html/rfc2822#section-3.6
> Add remaining address headers

- envelope.go
- envelope_test.go
- part.go
- testdata/mail/mime-bad-content-type.raw
- testdata/mail/mime-blank-media-name.raw
- testdata/mail/mime-duplicate-param.raw
If a duplicate param is present then parsing of the entire email fails. This fix handles a misplaced ";" in content-type. It also handles empty name in content-type. I have also added a unit test for this scenario.
> Fix for certain charset duplicate params error

- part.go
- quotedprint.go
- quotedprint_test.go
- testdata/parts/quoted-printable-invalid.raw
I ran into an issue today with the sanitizer. Another email from slack came through but this time it contained a url with query parameters. The '=' passes through to qp reader and fails. Here is my first pass. Thoughts?
> Handle unencoded equals in quoted printable sanitizer

- envelope.go
- envelope_test.go
When a binary only e.Root is created, the original header was not added to e.Root.Header.
> Missing SMTP header on binary only email.

- part.go
cf. issue "Add Unique ID's to Envelope's Parts" https://github.com/jhillyerd/enmime/issues/36
In my proposition, the Parts' PartIDs will look as such:
```
multipart/alternative                                       PartID = 0 (root)
|-- text/plain                                                    PartID = 1
|-- multipart/related                                        PartID = 2.0 ("multipart/")
|     |-- text/html                                               PartID = 2.1
|     |-- image/png, disposition: inline, filename: "img3.png"   PartID = 2.2
|     |-- multipart/related                                  PartID = 2.3.0 ("multipart/")
|     | `-- text/html                                            PartID = 2.3.1
|     `-- image/png, disposition: inline, filename: "img3.png"   PartID …
```
> Add Unique IDs to Envelope's Parts

- envelope.go
- part.go
cf. issue "Restore the Part's buffer after reading its content" https://github.com/jhillyerd/enmime/issues/38
> Restore the Part's buffer after reading its content

- part.go
For this [issue](https://github.com/jhillyerd/enmime/issues/42)
> Don't use CharsetReader when Part is attachement

- base64.go
- part.go
Inspired by python, for this [issure](https://github.com/jhillyerd/enmime/issues/46)
> Improve the tolerance of base64Cleaner

- encode.go
- encode_test.go
- testdata/encode/part-quoted-headers.golden
mime.FormatMediaType returns "" if the value is not a quoted-string as
per RFC 2616.
> encode: FileName must be quoted

- envelope.go
- envelope_test.go
- part.go
- part_test.go
I found an issue with yesterday's PR #66. By providing the parent part in the part.Clone() loop, references to newPart.Parent can be updated on the fly.
> fix part cloning, needs reference to parent in recursion

- envelope.go
- envelope_test.go
Currently, the `Content` of a BinaryOnlyMail is empty. It is possible to access the content with `env.Inlines[0].Content`, but this does not work in any case.
In my use case, I save all images from incoming messages. I do this with `DepthMatchAll()`. It returns a list of `Part`-objects. But in a BinaryOnlyMail there is no link between the `Part` and `env.Inlines[0]`. So without this patch, I see no way to access the content.
> Fix parseBinaryOnlyBody by adding Content

- envelope.go
- envelope_test.go
- example_test.go
This provides (roundabout) access to the `textproto.MIMEHeader` field of the `Envelope` struct. It's handy for various situations, like telling if there are optional DKIM or SPF headers.
> Add Envelope.GetHeaders()

- envelope.go
- envelope_test.go
- testdata/mail/non-mime-html-charset-header-only.raw
A chaset maybe set in header of HTML only emails, but not set in HTML
part. If a charset is set on HTML only email, use it to convert
content.
If Content-Type: text/html;charset="iso-8859-1" is set in mail header, but HTML body does not contain meta Content-Type, the body is not converted to utf-8.
> Bugfix HTML charset.

- envelope.go
- envelope_test.go
- testdata/mail/inlinemultipart.raw
If mail header is
Content-Type: multipart/mixed;...
Content-Disposition: inline
the resulting Envelope has an additional inline attachment with zero
bytes and a content type multipart/mixed. Changed test, so that
inlines with "multipart/" as content type prefix are not added to
inlines slice.
> Fix for multipart/mixed with inline disposition.

- error.go
- part.go
- part_test.go
- testdata/mail/html-only-inline.raw
- testdata/mail/non-mime-html.raw
This implements issue #81. Let me know if you think the content should also be decoded with the original charset, such that users can choose which one they want to use.
> detect charset of email parts

- header.go
- part.go
- part_test.go
- testdata/parts/barren-content-type.raw
An email was received with this Content-Type header:
```
Content-Type: ;
name=""
```
This change makes it so this MIME part can be parsed successfully.
> Resolves an issue parsing a malformed Content-Type header

- detect.go
- detect_test.go
- envelope.go
- header.go
- header_test.go
- part.go
- part_test.go
- testdata/parts/malformed-content-type-params.raw
Handled an issue when a content-type header like this is encountered:
`Content-Type: text/html;iso-8859-1`
> Handled malformed Content-Type params

- header.go
- header_test.go
- part_test.go
- testdata/parts/unquoted-ctype-param-special.raw
This allowed handling Content-Type headers with parameters that contain unquoted special characters, like this:
Content-Type: text/calendar; method=text/calendar
In that example, the `method` parameter contains a character that needs to be quoted (`/`), but is not.
This change reformats such parameters so they are quoted properly.
>  Fix content-type params with unquoted specials per RFC 2045, section 5.1

- part.go
- part_test.go
- testdata/parts/chardet-fail-non-txt.raw
- testdata/parts/chardet-fail.raw
Only attempt to detect character set on `text/*` parts
On failure to detect character set, fall back to part-specified character set (which is what was used prior to charset detection being introduced) and add a warning to the part rather than fail to parse the message.
> Better character set detection behavior

- encode.go
- encode_test.go
- testdata/encode/part-quotable-content.golden
In the case that a pre-existing part is decoded (e.g. from a pre-existing email), the content in an encoded part will be decoded correctly and the CTE header will be set based on the original part (e.g. quoted-printable). When encoding that part in the case that enmime's CTE detection decides that it should be 7bit, it did not remove the previous CTE header, resulting in a header specifying quoted-printable, but data that was encoded as 7bit.
> Remove CTE header if set in a part before encoding it.

- detect.go
- envelope.go
- header.go
- part.go
In this PR I am proposing to make our "ParseMediaType" function available in the public api. In my project I have needed this for a thin stdlib pre-parser, to distinguish if I should even bother sending the bytes to enmime. The kind of realworld nuances we have navigated in this function, and the ones we have yet to navigate, make me want to avoid copy 'n paste solution.
> Make ParseMediaType public

- header.go
- header_test.go
Only quoting the head of the attribute value and leaving the end unquoted was a hack. This will now properly tokenize the string, handle multiple RFC2047 chunks if present and quote both ends of the attribute value as needed.
> Implementation which does not depend on successive function calls

- detect.go
- detect_test.go
- testdata/mail/attachment-only-text-attachment.raw
Mail with content headers
Content-Type: text/plain; name="test.csv"
Content-Disposition: attachment; filename="test.csv"
is parsed incorrectly. The CSV attachment is used as text body.
> Propper detection of text/plain attachment.

- boundary.go
Resolves #127 
Actually I like this solution more, since the line-count has gone down
> #127 Refactor Read method on boundaryReader to avoid usage of UnreadByte()

- header.go
- header_test.go
While we handle media parameters with missing values if they are the last parameter, this fix allows for the handling of media parameters missing value in the middle of the parameter list.
> mime: invalid media parameter

- header.go
- header_test.go
Found occurrences of a media parameter list without a mime type, this will inject a safe default mime type.
> mime: expected slash after first token

- boundary.go
- boundary_test.go
Fixes the `boundaryReader` implementation of `io.Reader` to fill the slice based on its length, not its capacity. As per [the `io.Reader` documentation](https://pkg.go.dev/io?tab=doc#Reader).
> Read into destination by length, not capacity

- boundary.go
- boundary_test.go
When one MIME boundary immediately follows another, treat it as an empty part.
This comes from an issue I saw in a production environment where there was an email where a MIME part delimiter was immediately followed by a terminator. Like this:
```txt
Content-type: multipart/mixed; boundary="the-boundary"
--the-boundary
Content-type: text/plain
Some content.
--the-boundary
--the-boundary--
```
> Handle very empty MIME part

- encode.go
- encode_test.go
- part.go
- testdata/encode/part-default-headers.golden
- testdata/encode/part-quoted-headers.golden
- testdata/encode/part-quoted-printable-headers.golden
Custom ContentTypeParams are required in certain situations.
E.g. RFC3156 (MIME Security for OpenPGP) requires
protocol="application/pgp-encrypted" as Content-Type param.
> Adds Part.ContentTypeParams to allow custom params

- header.go
- header_test.go
results in "mime: invalid media parameter" error
This is a best effort attempt to correct an invalid continuation.
> Header line incorrectly beginning with a space

- header.go
- header_test.go
Hello. This is a fix for https://github.com/jhillyerd/enmime/issues/153.
If my understanding is correct, here is what was happening. When the `Content-Type` header value was something like `text/plain;`, it would turn into `text/plain;=not-a-param-value`, then `=not-a-param-value` parsed on its own would cause a `mime: invalid media parameter` error in turn.
Thanks!
> Handle trailing separators in header

- envelope.go
- envelope_test.go
- testdata/mail/mime-mixed-related.raw
i found outlook mail service genrate an eml struct like:
- multipart/mixed
- - multipart/related
- - - multipart/alternative
- - - - text/plain (real mail content)
- - - - text/html (real mail content)
- - multipart/alternative
- - - text/plain (contact info)
- - - text/html (contact info)
bfs(first) will locate the wrong html(contact info), i checked Apache mail common, using dfs(first) to locate html, btw macOS mail client and outlook client dfs all content, not just first
> fix: using dfs locate html body

- header.go
- ignore spaces when testing if a param is repeated
- closes #162
> fixMangledMediaType: improve repeated param check

- header.go
- header_test.go
String is expected to be iterated by bytes, but was by runes.
> fixUnescapedQuotes fixed for higher Unicode codepoints

- boundary.go
- boundary_test.go
- go.mod
- go.sum
Explicitly read/write a single byte rather than using `io.CopyN` to copy a single byte.
Before the change:
```
BenchmarkBoundaryReader-12    	  544516	      1909 ns/op	    6704 B/op	      15 allocs/op
```
After:
```
BenchmarkBoundaryReader-12    	 1039579	      1067 ns/op	    4495 B/op	       7 allocs/op
```
From 15 allocs/op down to 7.
Fixes #169.
> Improve performance of boundaryReader

- CHANGELOG.md
- builder.go
- builder_test.go
- example_test.go
- sender.go
- sender_test.go
This PR abstracts the sending of messages via SMTP, allowing users to substitute their own sending routines.  It also lets enmime and its users to test the sending of mail via mocks or fakes.
First step for #158 
*Warning:* This does change the builder API, will require new semantic release.
> Add an abstraction layer for sending messages

- builder.go
- builder_test.go
- error.go
References  #186
Only append To/BCC/CC if they have an address with a length. Added some tests.
The tests are slightly verbose as I couldn't think of a nice way of tabulating them, plus having the error message hard coded instead of as a referenceable error value feels strange.
> Validate To/BCC/CC Ref #186

- builder.go
- builder_test.go
This is valid for email systems and sometimes necessary, especially
when you don't have direct control over the souce input.
Fixes #160
> Builder: allow empty subject line

- header.go
- header_test.go
This is a fix for the problem of PR: [193](https://github.com/jhillyerd/enmime/pull/193)
Sorry for taking over, but I really need the fix :(
Let me know if there is anything you would like me to change.
Thanks for the package.
> Remove whitespace between parameter=value and ; in headers

- boundary.go
- boundary_test.go
Hi,
when there is a line longer than 4096 bytes, message parsing fails, because boundary reader returns bufio.ErrBufferFull.
This patch handles reading longer lines than 4096 bytes.
> Boundary reader - long lines processing fixed

- envelope_test.go
- header.go
- header_test.go
- testdata/mail/mime-bad-8bit-filename.raw
Hi,
I'm here with yet another RFC violation tolerance pull request. 
Some emails does not encode mime param with RFC 2047 encoding when they should. I.e when there are some characters with unicode value out of US-ASCII (> 127). Namely a chinese client Foxmail created such emails at least in the past.
I've improved the function `consumeParam` used by `fixUnquotedSpecials` to check for such violation and when it occurs, it encodes the value with RFC 2017. 
It's expected that the bytes are in UTF-8 encoding, but when not, the invalid bytes are encoded to base64 too. As a result,. `ReadEnvelope` does not end with error when an email with wrongly encoded attachment part is parsed and at least something (headers, body) is readable.
> ParseMediaType tolerates unencoded 8bit characters

- internal/coding/quotedprint.go
- internal/coding/quotedprint_test.go
Hi,
there is a bug in new QPCleaner implementation, which causes panic. When the `qp.lineLen` exceeds `MaxQPLineLen`, newline is safely inserted to `dest` buffer. But it is not checked, if `n` is still `< destLen` after this insertion, causing write after the end of `dest` in the following `switch` statement.
Here is a fix and test, the test causes panic on current version, the checks are there just for completeness.
Best regards
Pavel
> Fixed crash in QPCleaner, when line is too long and buffer is almost full

- mediatype/mediatype.go
- mediatype/mediatype_test.go
Added a very simple `fixNewlines` function to handle the following outlook produced case: 
```
{
label:  "Outlook-Logo with newlines",
input:  `application/octet-stream; name="=?utf-8?B?T3V0bG9vay1Mb2dvCgpEZXNj?="`,
mtype:  "application/octet-stream",
params: map[string]string{"name": "Outlook-Logo  Desc"},
},
```
> Fix newlines in mediatype.Parse

- mediatype/mediatype.go
- mediatype/mediatype_test.go
Hello,
I encountered some unknown email client in production. It used an invalid content type with extra parts, like `application/pdf/.pdf`
I `fixed` parsing by removing extra parts, but I'm not 100% sure it could be split as 
* `application` `pdf`
* `application` `pdf/.pdf`
* `application` `pdf-.pdf`
Thank you again for your great work
> fix(fixMangledMediaType) remove extra parts

- internal/coding/charsets.go
- part.go
support for untf8mb4, cp932
support more iso charsets
> Support more charsets

- mediatype/mediatype.go
- mediatype/mediatype_test.go
We came across a bad content type, which contained a doctype tag. This Change ignores it.
> Remove <!DOCTYPE tag in bad content types

- envelope_test.go
- example_test.go
- header.go
- header_test.go
- internal/coding/headerext.go
- testdata/mail/qp-utf8-header.raw
This PR fixes decoding addresses with quotes. 
For example, `"=?UTF-8?Q?Miros=C5=82aw_Marczak?="` should be decoded as `Mirosław Marczak`.
> fix: fix for quote-printed utf-8 header with quotes

- header.go
- header_test.go
Use extended parser for parsing "fixed" address list
> fix: use extended parser after fixing address list

- error.go
- error_test.go
- part.go
Hi,
I use enmime to parse emails in my service. It happened that instead of valid mime structure, client sent several MBs of base64 data as input. In such case, enmime consumes a lot of memory (several GBs). It's because `readHeader` function adds many many warnings in order to "Attempt to detect and repair a non-indented continuation of previous line" as comment says.
In the end, `readHeader` calls `ReadMIMEHeader`, which doesn't find valid MIME structure and fails with error and all these warnings are freed. However the memory peak remains and can lead to swapping.
To make it more robust, I'm adding a `MaxPartErrors` global public variable, which does not allow to record more than limit errors in one part. Default value is 1000 in my PR, but it can be also 0 if you desire, which means …
> Maximal number of errors recorded in Part limited

- envelope.go
- error.go
- options.go
- parser.go
- part.go
- part_test.go
- testdata/parts/multi-malformed.raw
This PR is proposal for the feature which allows to skip parts that can't be parsed. It won't return error, just add them to "problems"
This can be useful if you need to parse everything what is possible to parse and turned off by default.
For example, we have emails which have body of the email starting at the beginning of the part (without headers). Currently parser returns error,  but it can be beneficial to skip this part.
```
...
Content-Type: multipart/report; report-type=delivery-status;
boundary="12345/example.com"
Auto-Submitted: auto-generated (failure)
MIME-Version: 1.0
--12345/example.com
[EXTERNAL EMAIL]
The original message was received
...
```
> feat: add option skip malformed parts

- internal/coding/quotedprint.go
- internal/coding/quotedprint_test.go
In QPCleaner, write behind the buffer end could occur, when there was a `=XX` quoted printable token, line length was 1023 and remaining dest buffer space was only 1 byte. Because of line length, QPCleaner inserted `=\r\n`, but only the equal sign fit into the output buffer. The rest went to qp.overflow. 
Then the algorithm wrote to `dest[n]` without any additional checks, but `n` already pointed behind the buffer end.
Now the equal sign is also written to overflow in such situation.
I've also noticed, that qp.lineLength is not incremented when qp.overflow is put at the beginning of new buffer and also when `=` from quoted printable token is inserted. Seems as a bug to me, but I don't fix it in this PR.
> fix: buffer overrun when quoted printable is at the end of line and output buffer

- internal/coding/quotedprint.go
- internal/coding/quotedprint_test.go
Hi,
as mentioned in https://github.com/jhillyerd/enmime/pull/254, this fixes missing counting of `=` when quoted printable encoded char is processed.
I've also mentioned, that line length is not incremented, when `qp.overflow` is put into the buffer at the beginning of the next `Read`. Tests show it is not needed, because `qp.lineLength` is set, when `qp.overflow` is filled at the end of previous `Read`.
Regards
> fix: QPCleaner line length equal sign counting

- internal/stringutil/find.go
- internal/stringutil/find_test.go
- internal/stringutil/split.go
- internal/stringutil/split_test.go
- mediatype/mediatype.go
- mediatype/mediatype_test.go
This PR fixes splitting of Content-Type header, when parameter has semicolon inside quoted text`;`, e.g. `multipart/mixed; boundary="aaa;bbb;ccc"`. Previously, it was splitting wrongly, causing `fixUnescapedQuotes` function to break Content-Type header, making it `multipart/mixed; boundary=""`
Introduce new `FindQuoted` function. Reasoning: because for the splitting we still need to go through whole string, we can as well find all points where we need split. And then, use it for `IndexQuoted` or `CountQuoted` (analog of `strings.Index` and `strings.Count`), if we'll need it the future.
> fix(mediatype): quoted semicolon

- detect.go
- detect_test.go
- envelope.go
- envelope_test.go
- options.go
- parser.go
- part.go
- testdata/mail/multipart-wo-boundary.raw
Thit PR is a proposal to add option to treat multipart message without boundary as single-part.
For example message:
```
Content-Type: multipart/report;
I'm  multipart message without boundary
```
doesn't have boundary parameter in `Content-Type` header, but still can be parsed as single-part message.
Currently, parser returns error that it can't find boundary. With option turned on, parser will treat multipart messages without boundary as single-part.
> feat: add option to treat multipart w/o boundary as single-part

- options.go
- parser.go
- part.go
- part_test.go
- testdata/parts/extra-base64-character.raw
**What I did:**
I wrote a simple email which has two parts (text/plain and text/html) with base64 encoded data, but with one characteristic: both part contents have one extra base64 character (so they are slightly broken). Instead of having 4\*n characters, the contents are (4\*n)+1 characters long.
**What I expected:**
ReadParts() returns the root Part, with a FirstChild, and this one with a NextSibling. FirstChild and NextSibling have the partially decoded base64 data (Content != nil, parser recovers partial data from the parts with broken encoding).
**What I got:**
ReadParts() returns the root Part, with a FirstChild, and this one with a NextSibling. FirstChild and NextSibling have Content == nil (Parser does not recover partial data)
The reason is that for each part a …
> feat: ability to recover partial content from broken encoding

- dsn/dsn.go
- dsn/example_test.go
- dsn/parse.go
- dsn/parse_internal_test.go
- dsn/parse_test.go
- dsn/testdata/delayed_dsn.raw
- dsn/testdata/dsn_with_multipart_alternative.raw
- dsn/testdata/multi_recipient_dsn.raw
- dsn/testdata/simple_dsn.raw
- dsn/testdata/simple_dsn_with_html.raw
This PR adds parsing of Delivery Status Notification (DSN) per [rfc3464](https://datatracker.ietf.org/doc/html/rfc3464) and [rfc6522](https://datatracker.ietf.org/doc/html/rfc6522) (also known as [bounce message](https://en.wikipedia.org/wiki/Bounce_message)). 
Closes https://github.com/jhillyerd/enmime/issues/267
> feat: parse DSN

- flake.lock
- flake.nix
- shell.nix
> Use Go 1.20 from nixpkgs-unstable for dev shell

- .github/workflows/build-and-test.yml
- header.go
- header_test.go
> fix: Reject invalid MIME header name characters to support Go 1.20

- error.go
- error_test.go
- options.go
- parser.go
- part.go
Makes the `MaxPartErrors` global variable established in #240 available as an option.
> parser: Add MaxStoredPartErrors option

- inspect.go
- inspect_test.go
Exports coding.RFC2047Decode(), making the large set of charsets more readily available for package users.
> feat: export DecodeRFC2047 (#277)

- builder.go
- builder_test.go
Hello @jhillyerd and enmime maintainers,
I've been working on a feature enhancement for the enmime library to add support for multiple reply-to addresses, as described in RFC 5322, section 3.6.2. I believe this functionality will improve the flexibility of the library and provide users with the ability to correctly handle multiple reply-to addresses as per the email specification.
Here is a brief overview of the changes I've made in this commit:
- Updated the ``MailBuilder`` struct to store multiple reply-to addresses.
- Modified the ``Build`` function to correctly write multiple reply-to addresses.
- Updated the ``GetReplyTo`` function to return the first email in the list for backward compatibility, and added a new ``GetReplyToAddrs`` function to return a slice copy of all addresses.
- …
> feat: add support for multiple Reply-To addresses

- internal/coding/headerext.go
- mediatype/mediatype_test.go
We faced the issue that emails with encoded equal signs could not be parsed in certain cases. This fix should improve the situation. 
Thank you in advance for any code reviews and great library!
> fix for values with encoded equal signs

- boundary.go
- boundary_test.go
- builder.go
- cmd/mime-extractor/mime-extractor.go
- cmd/mime-extractor/mime-extractor_test.go
- envelope.go
- go.mod
- go.sum
- header.go
- inspect.go
- inspect_test.go
- internal/coding/charsets.go
- internal/coding/charsets_test.go
- internal/coding/quotedprint_test.go
- internal/test/golden.go
- mediatype/mediatype.go
- part.go
- Remove `github.com/pkg/errors`, which is archived since 2021.
- Remove `ioutil`, which is deprecated since Go 1.16
> Remove deprecated packages

- boundary.go
- boundary_test.go
- envelope.go
- go.mod
- go.sum
- header.go
- inspect.go
- mediatype/mediatype.go
- part.go
PR #298 removed usage of the archived package github.com/pkg/errors, and
references to the deprecated ioutil package.
After understanding that stdlib errors still does not support stack trace
wrapping (see discussion in #298), we have decided to rollback these changes
as parser debugging heavily benefits from stack traces.
The ioutil changes are desirable and will be kept.
See also #94
> Rollback pkg/errors portion of #298

- builder.go
- detect.go
- encode.go
- envelope.go
- header.go
- part.go
We did not intend for the external API to change when hosting our own version
of textproto.
Fixes #294
> MIMEHeader: use Go's net/textproto for public interface

- error.go
- header.go
The function is excellent at parsing SMTP and MIME headers. It would be great to use this function in other projects.
> Export readHeader as ReadHeader.

- detect.go
- detect_test.go
- envelope.go
- options.go
- options_test.go
- parser.go
- part.go
we've encountered real mail bodies where `Content-Type` is set to `"application/Pamir Viewer; name=\"some-thing.pmrv\""`, which is not RFC compliant, but is still valuable for us to process it, so it can't be skipped using `SkipMalformedParts`
New option `SetCustomParseMediaType` which accepts function which has signature exactly the same as `ParseMediaType`. This option can be utilized in similar scenarios, see provided example: `ExampleSetCustomParseMediaType`
will allow to fix this https://github.com/jhillyerd/enmime/issues/293 indirectly
> add new option SetCustomParseMediaType to customise mediatype parsing

- encode.go
- testdata/encode/parser-raw-content-option-true.raw.golden
Hi again, I missed this condition in my [last PR](https://github.com/jhillyerd/enmime/pull/304) sorry about that.
If we remove the "Content-Transfer-Encoding" header, the content may break.
> fix: don't remove CTE header when using the RawContent parser option

- mediatype/mediatype.go
- mediatype/mediatype_test.go
Looks like there was never a proper condition for filtering out empty parameters. It kinda worked thanks to this https://github.com/jhillyerd/enmime/blob/main/mediatype/mediatype.go#L125-L128 (`=` substring would always match if there was at least one parameter already added to `mtype`). It did not work if the empty parameter was the first parameter.
> feat: skip empty parameters

- inspect_test.go
- internal/textproto/reader.go
- internal/textproto/reader_email.go
- internal/textproto/reader_test.go
- internal/textproto/textproto.go
To allow for checking returned error types, types from the standard library's `net/textproto` must be used instead of types from the private `textproto` fork.
Kind of related to #294.
> Return public `net/textproto` error types

- encode.go
- encode_test.go
- testdata/encode/utf8-to.raw.golden
Hi, with this PR, I want to keep my header values like the original with the raw content parser option set to true.
> fix: don't encode header value with the RawContent parser option

- Makefile
- encode.go
- testdata/encode/part-default-headers.golden
- testdata/encode/part-file-mod-date.golden
- testdata/encode/part-quoted-headers.golden
- testdata/encode/part-quoted-printable-headers.golden
The tests are failing when ran in a TZ different from GMT.
```
--- FAIL: TestEncodePartDefaultHeaders (0.00s)
encode_test.go:71: Test output did not match testdata/encode/part-default-headers.golden
To update golden file, run: go test -update
encode_test.go:71: diff -want +got:
| Content-Disposition: attachment; filename=stuff.zip; modification-date="01
|- Feb 03 04:05 GMT"
|+ Feb 03 05:05 CET"
| Content-Id: <mycontentid>
| Content-Transfer-Encoding: base64
...
| WklQWklQWklQ
| 
```
This PR fixates test run to TZ=Europe/London
> chore: fixed timezone for tests

- encode.go
- testdata/encode/parser-raw-content-html-option-false.raw.golden
- testdata/encode/parser-raw-content-html-option-true.raw.golden
- testdata/encode/parser-raw-content-html-option.raw
Hi,
It's an improvement of the RawContent option to skip the function "setupMIMEHeaders" entirely. To avoid adding missing CTE header or try to correct them from the content.
> fix: do not setup MIME headers with the rawContent option set to true

- builder_test.go
- cmd/mime-extractor/mime-extractor_test.go
- cmd/utils.go
- encode_test.go
- envelope.go
- envelope_test.go
- inspect_test.go
- internal/coding/headerext.go
- internal/coding/idheader.go
- internal/stringutil/uuid_test.go
- internal/textproto/reader.go
- internal/textproto/reader_test.go
- style: use ReplaceAll instead of Replace
- encode_test: resolve several style warnings
- style: use require to appease testify linter
- textproto: ignore lint for stdlib api
- chore: remove unneeded sprintf calls
For #320
> chore: Resolve many linter warnings

- .github/workflows/lint.yml
- .golangci.yml
Starting with all linters, I have removed those that are inappropriate or infeasible entirely.  The linters that are commented out are aspirational -- they may require a lot of effort, or changes to the public API.
- golangci: update linter list
- use newer version of golangci-lint
Closes #320
> actions: update linter config

- options.go
- parser.go
- part.go
- part_test.go
- testdata/parts/chardet-detection.raw
This adds an option to disable character detection (when detected in the message part).
Resolves #340
> feat: add option to disable character detection

- Makefile
- flake.lock
- shell.nix
> chore: bump nix deps, remove deprecated golint

- .golangci.yml
- boundary.go
- builder_test.go
- cmd/mime-extractor/mime-extractor_test.go
- mediatype/mediatype.go
- mediatype/mediatype_test.go
- options_test.go
- part.go
- part_test.go
Renamed to `mediatype.ParseOptions`.  It is a breaking change, but the repetition forced us to keep some linters disabled.
Also resolve a number of warnings for re-enabled `revive` linter.
> fix!: rename mediatype.MediaTypeParseOptions to remove repetition

- .github/workflows/build-and-test.yml
- go.mod
> chore: bump min go version to 1.20

- error.go
- error_test.go
- options.go
- parser.go
Use `MaxStoredPartErrors` parser option instead
> chore!: remove deprecated MaxPartErrors global var

- error.go
- error_test.go
> chore!: remove deprecated Error.String method

- randoption_test.go
What I did:
run tests with `go test enmime`
What I got:
`--- FAIL: TestRandOption (0.00s)
randoption_test.go:22`
Release or branch I am using:
2.0.0
> Tests: TestRandOption fail

- internal/stringutil/addr.go
- internal/stringutil/addr_test.go
> fix: Handle spaces inside angle brackets

- encode.go
- encode_test.go
- encoder_options.go
- part.go
James, please look at the proposed changes. #358
> feat: encoding options added

- .github/workflows/lint.yml
> chore: bump golangci to last 1.x release

- .github/workflows/lint.yml
- .golangci.yml
> chore: bump golangci to 2.x
